### ISSUE TITLE
Failed to build --with-oracle with existing instantclient install?

### ISSUE THREAD

**Issue by bruth** [xo/homebrew-xo#1]
Hi, I ran:

```bash
brew install --with-oracle --with-odbc  usql
```

and it failed with the following output stating that `oci8` is not on the pkg-config path.

```bash
==> Installing usql from xo/xo
==> Downloading https://github.com/xo/usql/archive/v0.6.0.tar.gz
Already downloaded: /Users/ruthb/Library/Caches/Homebrew/usql-0.6.0.tar.gz
==> dep ensure --vendor-only
==> go build -tags most fts5 vtable json1 no_adodb oracle odbc -ldflags -s -w -X
Last 15 lines from /Users/ruthb/Library/Logs/Homebrew/usql/02.go:
most fts5 vtable json1 no_adodb oracle odbc
-ldflags
-s -w -X github.com/xo/usql/text.CommandVersion=v0.6.0
-o
/usr/local/Cellar/usql/0.6.0/bin/usql

# /usr/local/opt/pkg-config/bin/pkg-config --cflags oci8
Package oci8 was not found in the pkg-config search path.
Perhaps you should add the directory containing `oci8.pc'
to the PKG_CONFIG_PATH environment variable
No package 'oci8' found
/usr/local/opt/pkg-config/bin/pkg-config: exit status 1
# github.com/xo/usql/vendor/github.com/alexbrainman/odbc/api
ld: warning: directory not found for option '-L/opt/local/lib'
ld: warning: directory not found for option '-L/opt/local/lib'

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/xo/homebrew-xo/issues

/usr/local/Homebrew/Library/Homebrew/exceptions.rb:426:in `block in dump': undefined method `check_for_bad_install_name_tool' for #<Homebrew::Diagnostic::Checks:0x00000103059368> (NoMethodError)
Did you mean?  check_for_tap_ruby_files_locations
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:425:in `each'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:425:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:138:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `<main>'
```

However, it is:

```bash
$ /usr/local/opt/pkg-config/bin/pkg-config --cflags oci8
-I/usr/local/lib/instantclient_11_2/sdk/include/
```

**Comment by kenshaw** [comment]
I have not tried compiling against the Oracle 11g instantclient. My assumption would be that the database driver used, `ora`, would not work with it, considering that Oracle 11g is more than a decade old at this point. However, I have connected `usql` built with the 12g (the latest) instantclient, and have been able to connect, successfully, to older versions of the database. If you are unable to upgrade your Oracle database, then I'd suggest this approach, and use the 12g instantclient. It also is possible from the above debugging messages that the paths contained in your `oci8.pc` file are incorrect. You may want to try manually editing those paths.

Please note that I have packaged instantclient for use with Homebrew.

**Comment by bruth** [comment]
I totally missed the `brew tap xo/xo` and explicit install of the packaged `instantclient-sdk`. Apologies for that. I was able to install successfully. I just told brew to overwrite my existing files with the new symlinks. `usql` built properly after that. Thanks!
