### ISSUE TITLE
SHA256 mismatch

### ISSUE THREAD

**Issue by bennetfabian** [xo/homebrew-xo#13]
Latest commit https://github.com/xo/homebrew-xo/commit/19ac869285f531819bcc2db0e8856977a8d9e249 seems to have the wrong SHA256 checksum and therefore fails Homebrew's SHA256 check

```
Error: SHA256 mismatch
Expected: 1e6b48c7eacaf870e7cb1fe95835840b729e263e0d7cf489f05c73625a5cea7a
Actual: b2736ddfc597bbfd57d900f63e7cc56976100677a39c02fb4b9a0cada029ac0a
```

@kenshaw

**Comment by kenshaw** [comment]
This is due to GitHub's issues. Can't do anything about this at the moment.

**Comment by bennetfabian** [comment]
> This is due to GitHub's issues. Can't do anything about this at the moment.

Could you consider temporarily replacing the checksum with :no_check instead?

**Comment by kenshaw** [comment]
@bennetfabian have you tried updating to the latest version? I had rerun the announce pipeline prior to you posting this, and I tested the AUR + Homebrew repos. Both worked. I just retested both, and both are working.

**Comment by kenshaw** [comment]
@bennetfabian it would seem you likely have the old version of the file. You should clear your homebrew cache, as `b2736ddfc597bbfd57d900f63e7cc56976100677a39c02fb4b9a0cada029ac0a` is the correct sha256 hash for the file.

**Comment by bennetfabian** [comment]
Pretty weird. 5 minutes before opening this issue I actually cleared the cache. 
When it still mismatched after clearing the cache I just edited the checksum of the formula locally to stop Homebrew from complaining.

**Comment by kenshaw** [comment]
You likely need to do `brew update` then.

**Comment by bennetfabian** [comment]
> You likely need to do `brew update` then.

I also did that

Now it works 🤷‍♂️

**Comment by kenshaw** [comment]
@bennetfabian you likely did `brew update` some time yesterday (or the day before), and then only did `brew upgrade` after GitHub reverted their change, and before I updated the Homebrew formula for `usql`. Glad it works for you now.

**Comment by bennetfabian** [comment]
> @bennetfabian you likely did `brew update` some time yesterday (or the day before), and then only did `brew upgrade` after GitHub reverted their change, and before I updated the Homebrew formula for `usql`. Glad it works for you now.

That's probably how it went.
Thanks for your help at troubleshooting!
