### ISSUE TITLE
Can't find oci8 on install

### ISSUE THREAD

**Issue by derekslenk** [xo/homebrew-xo#2]
Trying to install via homebrew on macOS 10.13.

How to reproduce:
**➜  ~ brew tap xo/xo**
==> Tapping xo/xo
Cloning into '/usr/local/Homebrew/Library/Taps/xo/homebrew-xo'...
remote: Counting objects: 8, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 8 (delta 0), reused 5 (delta 0), pack-reused 0
Unpacking objects: 100% (8/8), done.
Tapped 3 formulae (35 files, 30.5KB)
**➜  ~ brew install --with-oracle --with-odbc usql**
==> Installing usql from xo/xo
==> Installing dependencies for xo/xo/usql: vgo, unixodbc
==> Installing xo/xo/usql dependency: vgo
==> Downloading https://github.com/golang/vgo/archive/93f360beebe966cc4548016d1f4f3a037ba9f022.tar.gz
Already downloaded: /Users/derek.slenk/Library/Caches/Homebrew/vgo-022.tar.gz
==> go build -o /usr/local/Cellar/vgo/022/bin/vgo
🍺  /usr/local/Cellar/vgo/022: 3 files, 11.7MB, built in 4 seconds
==> Installing xo/xo/usql dependency: unixodbc
==> Downloading https://homebrew.bintray.com/bottles/unixodbc-2.3.6.high_sierra.bottle.tar.gz
Already downloaded: /Users/derek.slenk/Library/Caches/Homebrew/unixodbc-2.3.6.high_sierra.bottle.tar.gz
==> Pouring unixodbc-2.3.6.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/unixodbc/2.3.6: 46 files, 1.8MB
==> Installing xo/xo/usql --with-oracle --with-odbc
==> Downloading https://github.com/xo/usql/archive/v0.7.0.tar.gz
Already downloaded: /Users/derek.slenk/Library/Caches/Homebrew/usql-0.7.0.tar.gz
==> vgo build -tags most fts5 vtable json1 no_adodb no_ql oracle odbc -ldflags -s -w -X github.com/xo/usql/text.CommandVersion=v0.7.0
Last 15 lines from /Users/derek.slenk/Library/Logs/Homebrew/usql/01.vgo:
vgo: downloading github.com/jackc/pgx v0.0.0-20180517214546-870744921917
vgo: downloading github.com/lib/pq v0.0.0-20180523175426-90697d60dd84
vgo: downloading github.com/prestodb/presto-go-client v0.0.0-20180604210701-a80ce5f9dc7f
vgo: downloading github.com/SAP/go-hdb v0.12.0
vgo: downloading golang.org/x/text v0.3.0
vgo: downloading github.com/mattn/go-sqlite3 v1.7.0
vgo: downloading github.com/xo/xoutil v0.0.0-20171112033149-46189f4026a5
vgo: downloading github.com/VoltDB/voltdb-client-go v1.0.1
**_vgo: downloading github.com/spaolacci/murmur3 v0.0.0-20180118202830-f09979ecbc72
# /usr/local/opt/pkg-config/bin/pkg-config --cflags oci8
Package oci8 was not found in the pkg-config search path.
Perhaps you should add the directory containing `oci8.pc'
to the PKG_CONFIG_PATH environment variable
No package 'oci8' found
/usr/local/opt/pkg-config/bin/pkg-config: exit status 1_**

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/xo/homebrew-xo/issues

**Comment by solankip** [comment]
Same issue with macOS version 10.12.6

**Comment by kenshaw** [comment]
Homebrew removed the `:run` `depends_on` option, which is what the usql formula originally used. Can you try manually installing the `instantclient-sdk` formula and then rerunning the install?

```
$ brew install instantclient-sdk
$ brew install usql --with-oracle
```

**Comment by kenshaw** [comment]
This is now fixed. Please update homebrew and try again:

```sh
$ brew update && brew install usql --with-oracle --with-odbc
```
